---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
  - values.yaml

  tasks:
  - name: Upload Cert
    tags:
    - cert
    community.aws.iam_cert:
      name: wap_wildcard_cert
      state: present
      cert: "{{ lookup('file', './certs/server.crt') }}"
      key: "{{ lookup('file', './certs/server.key') }}"
  
  - name: Render CF Config
    tags:
    - template
    template:
       src: ./templates/wap_cf_stack.yaml.j2
       dest: wap_cf_stack.yaml
       lstrip_blocks: yes

  - name: Upload CF Template
    tags:
    - deploy
    amazon.aws.cloudformation:
      capabilities:
      - "CAPABILITY_NAMED_IAM" 
      stack_name: "nginx-wap-{{ Environment }}"
      state: "present"
      region: "{{ Region }}"
      disable_rollback: no
      template: "wap_cf_stack.yaml"
      template_parameters:
        needsServiceLinkedRole: "{{ needsServiceLinkedRole }}"
        needsTaskExecutionRole: "{{ needsTaskExecutionRole }}"

