# Whether this stacks resources should be deleted when the stack is.
# can be Delete or Retain    
DeletePolicy: Retain

Environment: devtest
# The AWS region the resources will deploy to
Region: us-west-2

# The ID of the VPC to use. The ID, not the name
Vpc: vpc-099919f97e876cc5a

# The id of the subnets to deploy to. Should be in different availability zones, and associated
# with the vpc defined above.
Subnet1: subnet-0ddfc2a6d626d910f
Subnet2: subnet-0528d4ba2ae4ba272

# The ports needed by this WAP. 
NeededPorts:
- 1442
- 1443
- 1444
- 1446
- 1447
- 444
- 88

# URL of the container image
Image: 077808477023.dkr.ecr.us-west-2.amazonaws.com/nginx-wap-devtest:latest

# Whether or not we should creat a service linked role for ecs for this aws account. Can be true
# to create the role or false to not. If unsure, look in iam for a role called AWSServiceRoleForECS.
# If it exists set this var to false, otherwise true.
needsServiceLinkedRole: "false"

#similar to above, except for task execution role. This will be true if this is the first deployment
#if you have a test deployment already, and are deploying prod for instance, you can set to false.
needsTaskExecutionRole: "false"
